# Travis CI configuration file.
# @link https://travis-ci.org/

# For use with the Twenty Sixteen WordPress theme
# @link https://github.com/WordPress/twentysixteen/

# Declare project language and PHP versions to test against.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
php:
    - "7.0"

# Ditch sudo and use containers.
# @link http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
# @link http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: false

# Declare which versions of WordPress to test against.
# Also declare whether or not to test in Multisite.
env:
    # Trunk (current version in development)
    # @link https://github.com/WordPress/WordPress
    - WP_VERSION=master WP_MULTISITE=1
